# FROM golang:1.20-alpine

# WORKDIR /app

# COPY go.mod go.sum ./
# RUN go mod download

# COPY . .

# RUN go build -o main .

# EXPOSE 8080
# CMD ["./main"]
FROM golang:1.20-alpine

# Install necessary tools
RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
# RUN ls -R /app/mail/templates

RUN go build -o main ./cmd

EXPOSE 8080
CMD ["./main"]
